mytag/urls.py
from django.contrib import admin
from django.urls import path, include

# my import
from django.conf import settings
from django.conf.urls.static import static

from home_comments.views import comment_partial_view
from home_newsletters.views import news_letters_partial_view
from .views import home_page
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', home_page, name='starting_page'),
    path('', include('mytag_cards.urls', namespace='mytag_cards')),
    path('', include('mytag_account.urls', namespace='account')),
    path('', include('products_order.urls', namespace='products_order')),
    path('product', include('home_products.urls', namespace='home_product')),
    path('comment', comment_partial_view, name='comment'),
    path('newsletters', news_letters_partial_view, name='newsletters'),
    path('userpanel', include('userpanel.urls', namespace='userpanel')),
    path('userpanel/', include('userpanel_mytag.urls', namespace='userpanel_mytag')),
    path('userpanel/', include('userpanel_profile.urls', namespace='userpanel_profile')),
    path('userpanel/', include('userpanel_changepassword.urls', namespace='userpanel_changepassword')),
    path('userpanel/', include('userpanel_map.urls', namespace='userpanel_map')),
    path('userpanel/', include('userpanel_invoice.urls', namespace='userpanel_invoice')),
    path('admin/', admin.site.urls),

]
if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userpanel_profile/urls.py
from django.urls import path
from .views import Profile, profile_view

app_name = 'userpanel_profile'
urlpatterns = [
    path('profile/update', Profile, name='Profile'),
    path('profile/', profile_view, name='views'),
]

userpanel_profile/forms.py
from django import forms


class UserForm(forms.Form):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'لطفا نام خود را وارد نمایید', 'class': 'form-control'}),
        label='نام'
    )

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'لطفا نام خانوادگی خود را وارد نمایید', 'class': 'form-control'}),
        label='نام خانوادگی'
    )
    PhoneNumber = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'لطفا نام خانوادگی خود را وارد نمایید', 'class': 'form-control'}),
        label='موبایل'
    )
    profile = forms.ImageField(
        label='پروفایل'
    )


class UserViewForm(forms.Form):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'لطفا نام خود را sایید', 'class': 'form-control', 'disabled': 'True',
                   'readonly': 'True'}),
        label='نام'
    )

    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'لطفا نام خانوادگی خود را وارد نمایید', 'class': 'form-control', 'disabled': 'True',
                   'readonly': 'True'}),
        label='نام خانوادگی'
    )
    PhoneNumber = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'لطفا نام خانوادگی خود را وارد نمایید', 'class': "btn btn-primary",
                   'disabled': 'True',
                   'readonly': 'True'}),
        label='پروفایل'
    )
    profile = forms.CharField()

userpanel_profile/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from userpanel_profile.forms import UserForm


@login_required(login_url='/login')
def Profile(request):
    context = {}
    if request.method == "GET":
        User_Form = UserForm(request.POST or None, initial={
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'PhoneNumber': request.user.PhoneNumber,
            'profile': request.user.profile,

        })
        context['User_Form'] = User_Form
    if request.method == "POST":
        User_Form = UserForm(request.POST or None, request.FILES, initial={
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'PhoneNumber': request.user.PhoneNumber,
            'profile': request.user.profile,

        })
        if User_Form.is_valid():
            User_edit = User.objects.filter(id=request.user.id).first()
            first_name = User_Form.cleaned_data.get('first_name')
            last_name = User_Form.cleaned_data.get('last_name')
            PhoneNumber = User_Form.cleaned_data.get('PhoneNumber')
            profile = User_Form.cleaned_data.get('profile')
            User_edit.profile = profile
            User_edit.first_name = first_name
            User_edit.last_name = last_name
            User_edit.PhoneNumber = PhoneNumber
            User_edit.save()
        return redirect(reverse('userpanel_profile:views'))

    return render(request, 'userpanel_profile/user_panel_profile_update.html', context)


@login_required(login_url='/login')
def profile_view(request):
    user = User.objects.filter(pk=request.user.pk).first()
    context = {
        'user': user
    }
    return render(request, 'userpanel_profile/user_panel_profile_view.html', context)

userpanel_profile/templates/userpanel_profile/user_panel_profile_update.html
{% extends 'shared/userpanel/_MainLayout.html' %}

{% block content %}
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">ویرایش پروفایل</h3>
                    </div>
                    <div class="box-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ User_Form.profile.label }}
                            {{ User_Form.profile }}
                            <br>
                            {{ User_Form.first_name.label }}
                            {{ User_Form.first_name }}
                            <br>
                            {{ User_Form.last_name.label }}
                            {{ User_Form.last_name }}
                            <br>
                            {{ User_Form.PhoneNumber.label }}
                            {{ User_Form.PhoneNumber }}
                            <br>
                            <button type="submit" class="btn btn-primary">ذخیره</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

userpanel_profile/templates/userpanel_profile/user_panel_profile_view.html
{% extends 'shared/userpanel/_MainLayout.html' %}

{% block content %}
    <div class="col-md-4">
        <!-- Widget: user widget style 1 -->
        <div class="box box-widget widget-user">
            <!-- Add the bg color to the header using any of the bg-* classes -->
            <div class="widget-user-header bg-aqua-active">
                <h3 class="widget-user-username">
                    {% if user.first_name %}
                        {{ user.first_name }}
                    {% else %}
                        بدون نام
                    {% endif %}
                    {% if user.last_name %}
                        {{ user.last_name }}
                    {% else %}
                        بدون نام خانودگی
                    {% endif %}
                </h3>
            </div>

            <div class="widget-user-image">
                <img class="img-circle" src="{{ user.profile.url }}" alt="پروفایل کاربر">
            </div>
            <div class="box-footer">
                {% if user.PhoneNumber %}
                    موبایل:  {{ user.PhoneNumber }}
                {% endif %}
                <br>
                <br>
                {% if user.email %}
                    ایمیل: {{ user.email }}
                {% endif %}
                <br>
                <br>
                <a href="{% url 'userpanel_profile:Profile' %}">ویرایش</a>
                <!-- /.row -->
            </div>
        </div>
        <!-- /.widget-user -->
    </div>
{% endblock %}