mytag/urls.py
from django.contrib import admin
from django.urls import path, include

# my import
from django.conf import settings
from django.conf.urls.static import static

from home_comments.views import comment_partial_view
from home_newsletters.views import news_letters_partial_view
from .views import home_page
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', home_page, name='starting_page'),
    path('', include('mytag_cards.urls', namespace='mytag_cards')),
    path('', include('mytag_account.urls', namespace='account')),
    path('', include('products_order.urls', namespace='products_order')),
    path('product', include('home_products.urls', namespace='home_product')),
    path('comment', comment_partial_view, name='comment'),
    path('newsletters', news_letters_partial_view, name='newsletters'),
    path('userpanel', include('userpanel.urls', namespace='userpanel')),
    path('userpanel/', include('userpanel_mytag.urls', namespace='userpanel_mytag')),
    path('userpanel/', include('userpanel_profile.urls', namespace='userpanel_profile')),
    path('userpanel/', include('userpanel_changepassword.urls', namespace='userpanel_changepassword')),
    path('userpanel/', include('userpanel_map.urls', namespace='userpanel_map')),
    path('userpanel/', include('userpanel_invoice.urls', namespace='userpanel_invoice')),
    path('admin/', admin.site.urls),

]
if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mytag_account/urls.py
from django.urls import path, include, reverse_lazy

from mytag_account.views import user_login_page, user_register_page, ResetPasswordView, activate, logout
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('login', user_login_page, name='login'),
    path('register', user_register_page, name='register'),
    path('account/activate/<uidb64>/<token>', activate, name='activate'),
    path('account/password_reset/',
         auth_views.PasswordResetView.as_view(template_name='mytag_account/password_reset_form.html',
                                              email_template_name='mytag_account/password_reset_email.html',
                                              success_url=reverse_lazy('account:password_reset_done')),
         name='password_reset'),

    path('account/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='mytag_account/password_reset_done.html'),
         name='password_reset_done'),

    path('account/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="mytag_account/password_reset_confirm.html",
                                                     success_url=reverse_lazy('account:password_reset_complete')),
         name='password_reset_confirm'),
    path('account/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='mytag_account/password_reset_complete.html'),
         name='password_reset_complete'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
]

userpanel/urls.py
from django.urls import path, include
from .views import user_panel_home_page

app_name = 'userpanel'
urlpatterns = [
    path('', user_panel_home_page, name='user-home-page'),
]

templates/shared/home/Footer.html
{% load static %}
<footer class="footer" id="footer">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="footer-info-area">
                    <div class="footer-logo">
                        <a href="#" class="logo-link">
                            <img src="{% static 'img/logodgtag.png' %}" alt="لوگو دی جی تگ">
                        </a>
                    </div>
                    <div class="text">
                        <p>هر گونه کپی برداری و انتشار غیرقانونی از سایت پیگرد قانونی دارد.
                        </p>
                    </div>
                </div>
                <div class="fotter-social-links">
                    <ul>
                        <li>
                            <a href="#" class="facebook">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="twitter">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="linkedin">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="google-plus">
                                <i class="fab fa-google-plus-g"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="dribbble">
                                <i class="fab fa-dribbble"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="copy-bg text-center">
        <p>
            © 2020 <a href="http://www.dgtag.ir">پیرولی</a> تمام حقوق مادی و
            معنوی سایت محفوظ می باشد.
        </p>
    </div>
</footer>

templates/shared/home/_FooterReferences.html
{% load static %}
<!-- jquery -->
<script src="{% static 'js/jquery.js' %}"></script>
<!-- popper -->
<script src="{% static 'js/popper.min.js' %}"></script>
<!-- bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- way poin js-->
<script src="{% static 'js/waypoints.min.js' %}"></script>
<!-- owl carousel -->
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<!-- magnific popup -->
<script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
<!-- aos js-->
<script src="{% static 'js/aos.js' %}"></script>
<!-- counterup js-->
<script src="{% static 'js/jquery.countdown.min.js' %}"></script>
<!-- easing js-->
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<!-- Map js -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC7eALQrRUekFNQX71IBNkxUXcz-ALS-MY&amp;sensor=false"></script>
<script src="{% static 'js/gmap.js' %}"></script>
<!-- main -->
<script src="{% static 'js/contact.js' %}"></script>
<!-- main -->
<script src="{% static 'js/main.js' %}"></script>

templates/shared/home/_HeaderReferences.html
{% load static %}
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- favicon -->
<link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/apple-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/apple-icon-60x60.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/apple-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon-76x76.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/apple-icon-120x120.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/apple-icon-144x144.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/apple-icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-icon-180x180.png' %}">
<link rel="icon" type="image/png" sizes="192x192"  href="{% static 'img/android-icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'img/manifest.json' %}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{% static 'img/ms-icon-144x144.png' %}">
<meta name="theme-color" content="#ffffff">
<!-- bootstrap -->
<link rel="stylesheet" href="{% static 'css/bootstrap-rtl.min.css' %}">
<!-- fontawesome -->
<link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
<!-- Flat Icon -->
<link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
<!-- animate -->
<link rel="stylesheet" href="{% static 'css/animate.css' %}">
<!-- Owl Carousel -->
<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<!-- magnific popup -->
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
<!-- AOS css -->
<link rel="stylesheet" href="{% static 'css/aos.css' %}">
<!-- stylesheet -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<!-- responsive -->
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">

templates/shared/home/_MainLayout.html
{% load static %}
<!doctype html>
<html lang="fa">
<head>

    <title>{% block title %}دی جی تگ{% endblock %}</title>
    {% include 'shared/home/_HeaderReferences.html' %}
    {% block productshead %}{% endblock %}
</head>

<body {% block class_body %}{% endblock %}>

<!-- preloader area start -->
<!-- <div class="preloader" id="preloader">
  <div class="preloader-inner">
    <div class="cube-wrapper">
      <div class="cube-folding">
        <span class="leaf1"></span>
        <span class="leaf2"></span>
        <span class="leaf3"></span>
        <span class="leaf4"></span>
      </div>
      <span class="loading" data-name="Loading">در حال بارگذاری
      </span>
    </div>
  </div>
</div> -->
<!-- preloader area end -->
{% include 'shared/home/_Navbar.html' %}

{% block body_contect %}

{% endblock %}

{% include 'shared/home/Footer.html' %}

{% include 'shared/home/_FooterReferences.html' %}
{% block productfoot %}{% endblock %}
</body>
</html>

templates/shared/home/_Navbar.html
{% load static %}
<header class="navigation">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 p-0">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="navbar-brand" href="{% url 'starting_page' %}">
                        <img src="{% static 'img/logodgtag.png' %}" alt="">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainmenu"
                            aria-controls="mainmenu" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="mainmenu">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'starting_page' %}">صفحه اصلی</a>
                            </li>
                            <li class="nav-item">
                                {% if  request.path == "/" %}
                                    <a class="nav-link" href="#about">درباره ما</a>
                                {% else %}
                                    <a class="nav-link" href="{% url 'starting_page' %}#about">درباره ما</a>
                                {% endif %}
                            </li>
                            <li class="nav-item">

                                {% if  request.path == "/" %}
                                    <a class="nav-link" href="#feature">ویژگی ها</a>
                                {% else %}
                                    <a class="nav-link" href="{% url 'starting_page' %}#feature">ویژگی ها</a>
                                {% endif %}
                            </li>
                            <li class="nav-item">
                                {% if  request.path == "/" %}
                                    <a class="nav-link" href="#pricing">محصولات</a>
                                {% else %}
                                    <a class="nav-link" href="{% url 'starting_page' %}#pricing">محصولات</a>
                                {% endif %}

                            </li>
                            <li class="nav-item dropdown ">
                                <a class="nav-link active dropdown-toggle" role="button" data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    صفحات
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="blog-grid.html"
                                    ><i class="fas fa-chevron-left"></i> وبلاگ سه شبکه
                                        ای</a
                                    >
                                    <a class="dropdown-item" href="blog-sidebar.html"
                                    ><i class="fas fa-chevron-left"></i>وبلاگ با نوار
                                        کناری</a
                                    >
                                    <a
                                            class="dropdown-item"
                                            href="blog-details-with-sidebar.html"
                                    ><i class="fas fa-chevron-left"></i>جزئیات وبلاگ با
                                        نوار کناری</a
                                    >
                                    <a class="dropdown-item" href="blog-details.html"
                                    ><i class="fas fa-chevron-left"></i>جزئیات وبلاگ</a
                                    >
                                    <a class="dropdown-item" href="login.html"
                                    ><i class="fas fa-chevron-left"></i>وارد شدن</a
                                    >
                                    <a class="dropdown-item" href="register.html"
                                    ><i class="fas fa-chevron-left"></i>ثبت نام</a
                                    >
                                    <a class="dropdown-item" href="forgot-pass.html"
                                    ><i class="fas fa-chevron-left"></i>فراموشی رمز عبور</a
                                    >
                                    <a class="dropdown-item" href="404.html"
                                    ><i class="fas fa-chevron-left"></i>404</a
                                    >
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#testimonial-area">سفارش</a>
                            </li>
                            <li class="nav-item">
                                {% if  request.path == "/" %}
                                    <a class="nav-link" href="#faq">پرسش و پاسخ</a>
                                {% else %}
                                    <a class="nav-link" href="{% url 'starting_page' %}#faq">پرسش و پاسخ</a>
                                {% endif %}

                            </li>
                            <li class="nav-item">
                                {% if  request.path == "/" %}
                                    <a class="nav-link" href="#contact">ارتباط با ما</a>
                                {% else %}
                                    <a class="nav-link" href="{% url 'starting_page' %}#contact">ارتباط با ما</a>
                                {% endif %}

                            </li>
                            {% if request.user.is_authenticated %}

                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'userpanel:user-home-page' %}">حساب کاربری</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account:login' %}">ورود</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account:register' %}">عضویت</a>
                                </li>
                            {% endif %}

                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>

templates/shared/home/_SidePage.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <title>{% block title %}دی جی تگ{% endblock %}</title>
    {% include 'shared/home/_HeaderReferences.html' %}
</head>

<body {% block calss_body %}{% endblock %}>

{% include 'shared/home/_Navbar.html' %}

{% block body_contect %}

{% endblock %}

{% include 'shared/home/Footer.html' %}

{% include 'shared/home/_FooterReferences.html' %}

</body>
</html>