mytag/urls.py
from django.contrib import admin
from django.urls import path, include

# my import
from django.conf import settings
from django.conf.urls.static import static

from home_comments.views import comment_partial_view
from home_newsletters.views import news_letters_partial_view
from .views import home_page
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', home_page, name='starting_page'),
    path('', include('mytag_cards.urls', namespace='mytag_cards')),
    path('', include('mytag_account.urls', namespace='account')),
    path('', include('products_order.urls', namespace='products_order')),
    path('product', include('home_products.urls', namespace='home_product')),
    path('comment', comment_partial_view, name='comment'),
    path('newsletters', news_letters_partial_view, name='newsletters'),
    path('userpanel', include('userpanel.urls', namespace='userpanel')),
    path('userpanel/', include('userpanel_mytag.urls', namespace='userpanel_mytag')),
    path('userpanel/', include('userpanel_profile.urls', namespace='userpanel_profile')),
    path('userpanel/', include('userpanel_changepassword.urls', namespace='userpanel_changepassword')),
    path('userpanel/', include('userpanel_map.urls', namespace='userpanel_map')),
    path('userpanel/', include('userpanel_invoice.urls', namespace='userpanel_invoice')),
    path('admin/', admin.site.urls),

]
if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userpanel_mytag/urls.py
from django.urls import path, include
from .views import HomepageView, MyTagDetailView, MyTagCreate, MyTagUpdate, MyTagDelete

app_name = 'userpanel_mytag'
urlpatterns = [
    path('mytag/', HomepageView.as_view(), name='homepage'),
    path('mytag/<int:pk>/', MyTagDetailView.as_view(), name='detail'),
    path('mytag/create/', MyTagCreate, name='create'),
    path('mytag/update/<int:pk>/', MyTagUpdate.as_view(), name='update'),
    path('mytag/delete/<int:pk>/', MyTagDelete.as_view(), name='delete'),
]

userpanel_mytag/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Field, Fieldset, HTML, ButtonHolder, Submit
from django.contrib.auth.models import User

from mytag_cards.models import Card
from django import forms
from django.forms.models import inlineformset_factory

from mytag_cards_contactnumbers.models import ContactNumbers
from mytag_cards_socialnetworks.models import SocialNetwork
from userpanel_mytag.custom_layout_object import Formset


#
# # class CardForm(forms.ModelForm):
# #     class Meta:
# #         model = Card
# #         widgets = {
# #             'FirstName': forms.TextInput(attrs={'class': 'form-control'}),
# #             'LastName': forms.TextInput(attrs={'class': 'form-control'}),
# #             'Company': forms.TextInput(attrs={'class': 'form-control'}),
# #             'WorkName': forms.TextInput(attrs={'class': 'form-control'}),
# #             'Bio': forms.Textarea(attrs={'class': 'form-control'}),
# #             'UserName': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'نام کاربری'}),
# #
# #         }
# #
# #         fields = (
# #             'ProfileImg',
# #             'FirstName',
# #             'LastName',
# #             'Company',
# #             'WorkName',
# #             'Bio',
# #             'UserName',
# #         )
# #
# #
# # class ContactNumbersForm(forms.ModelForm):
# #     class Meta:
# #         model = ContactNumbers
# #         fields = ('Name', 'Number', 'Type')
# #         widgets = {
# #             'Name': forms.TextInput(attrs={'class': 'form-control'}),
# #             'Number': forms.TextInput(attrs={'class': 'form-control'}),
# #             'Type': forms.Select(attrs={'class': 'form-control'}),
# #
# #         }
# #
# #
# # CardFormset = inlineformset_factory(
# #     Card,
# #     ContactNumbers,
# #     form=ContactNumbersForm,
# #     extra=5,
# #     # max_num=5,
# #     # fk_name=None,
# #     # fields=None, exclude=None, can_order=False,
# #     # can_delete=True, max_num=None, formfield_callback=None,
# #     # widgets=None, validate_max=False, localized_fields=None,
# #     # labels=None, help_texts=None, error_messages=None,
# #     # min_num=None, validate_min=False, field_classes=None
# #
# # )
# #
#
# class ContactNumbersForm(forms.ModelForm):
#     class Meta:
#         model = ContactNumbers
#         exclude = ()
#         fields = (
#             'Name',
#             'Number',
#             'Type'
#         )
#         widgets = {
#             'Name': forms.TextInput(attrs={'class': 'form-control'}),
#             'Number': forms.TextInput(attrs={'class': 'form-control'}),
#             'Type': forms.Select(attrs={'class': 'form-control'}),
#
#         }
#
#
# # class SocialNetworkForm(forms.ModelForm):
# #     class Meta:
# #         model = SocialNetwork
# #         exclude = ()
# #         fields = (
# #             'Name',
# #             'Url',
# #             'Type',
# #
# #         )
# #         widgets = {
# #             'Name': forms.TextInput(attrs={'class': 'form-control'}),
# #             'Url': forms.TextInput(attrs={'class': 'form-control'}),
# #             'Type': forms.Select(attrs={'class': 'form-control'}),
# #
# #         }
#
#
# class CardForm(forms.ModelForm):
#     class Meta:
#         model = Card
#         exclude = ['created_by', ]
#         fields = (
#             'ProfileImg',
#             'FirstName',
#             'LastName',
#             'Company',
#             'WorkName',
#             'Bio',
#             'UserName',
#         )
#
#     def __init__(self, *args, **kwargs):
#         super(CardForm, self).__init__(*args, **kwargs)
#         self.helper = FormHelper()
#         self.helper.form_tag = True
#         self.helper.form_class = 'role="form"'
#         self.helper.label_class = 'col-md-3 create-label'
#         self.helper.field_class = 'form-group'
#         self.helper.layout = Layout(
#
#             # Div(
#             #     Field('ProfileImg'),
#             #     Field('FirstName'),
#             #     Field('LastName'),
#             #     Field('Company'),
#             #     Field('Bio'),
#             #     Field('UserName'),
#             # Fieldset('شماره ها', Formset('titles')),
#             #     # HTML("<br>"),
#             #     ButtonHolder(Submit('submit', 'دخیره')),
#             # ),
#             Div(
#                 Div(
#                     Field('ProfileImg'),
#                     css_class='form-group'
#                 ),
#                 Div(
#                     Field('FirstName', css_class='form-control'),
#                     css_class='form-group'
#                 ),
#                 Div(
#                     Field('LastName', css_class='form-control'),
#                     css_class='form-group'
#                 ),
#                 Div(
#                     Field('Company', css_class='form-control'),
#                     css_class='form-group'
#                 ),
#                 Div(
#                     Field('Bio'),
#                     css_class='form-group'
#                 ),
#                 Div(
#                     Field('UserName'),
#                     css_class='form-group'
#                 ),
#                 Div(
#                     Fieldset('شماره ها', Formset('titles')),
#                     css_class='form-group'
#                 ),
#                 # Div(
#                 #     Fieldset('شماره ها', Formset('cards')),
#                 #     css_class='form-group'
#                 # ),
#                 ButtonHolder(Submit('submit', 'دخیره')),
#             )
#
#         )
#
#
# CardFormset = inlineformset_factory(
#     Card,
#     ContactNumbers,
#     form=ContactNumbersForm,
#     fields=['Name', 'Number', 'Type'],
#     extra=2,
#     # can_delete=True,
# )
#
# # CardSocialNetworkFormset = inlineformset_factory(
# #     Card,
# #     SocialNetwork,
# #     form=SocialNetworkForm,
# #     fields=['Name', 'Url', 'Type'],
# #     extra=2,
# #     # can_delete=True,
# # )


class ContactNumbersForm(forms.ModelForm):
    class Meta:
        model = ContactNumbers
        exclude = ()


ContactNumbersFormSet = inlineformset_factory(
    Card, ContactNumbers, form=ContactNumbersForm,
    fields=['Name', 'Number', 'Type'], extra=3, can_delete=False
)


class CardSocialNetworkForm(forms.ModelForm):
    class Meta:
        model = SocialNetwork
        exclude = ()


CardSocialNetworkFormset = inlineformset_factory(
    Card, SocialNetwork, form=CardSocialNetworkForm,
    fields=['Name', 'Url', 'Type'], extra=3, can_delete=False
)


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        widgets = {
            'FirstName': forms.TextInput(attrs={'class': 'form-control'}),
            'LastName': forms.TextInput(attrs={'class': 'form-control'}),
            'Company': forms.TextInput(attrs={'class': 'form-control'}),
            'WorkName': forms.TextInput(attrs={'class': 'form-control'}),
            'Bio': forms.Textarea(attrs={'class': 'form-control'}),
            'UserName': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'نام کاربری'}),
        }

        fields = ('ProfileImg', 'FirstName', 'LastName', 'Company', 'WorkName', 'Bio', 'UserName')
        exclude = ['created_by', ]

    def __init__(self, *args, **kwargs):
        super(CardForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        # self.helper.form_class = 'form-horizontal'
        # self.helper.label_class = 'col-md-3 create-label'
        # self.helper.field_class = 'col-md-9'
        
        self.helper.layout = Layout(
            Div(
                Field('ProfileImg'),
                Field('FirstName'),
                Field('LastName'),
                Field('Company'),
                Field('WorkName'),
                Field('Bio'),
                Field('UserName'),
                Fieldset('شبکه های اجتماعی',
                         Formset('cards')),
                Fieldset('شماره ها',
                         Formset('titles')),
                HTML("<br>"),
                ButtonHolder(Submit('submit', 'ذخیره')),
            )
        )

userpanel_mytag/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.db import transaction, IntegrityError
# Create your views here.
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, DetailView, CreateView, UpdateView, DeleteView

from mytag_cards.models import Card
from userpanel_mytag.forms import CardForm, ContactNumbersFormSet, CardSocialNetworkFormset


@method_decorator(login_required(login_url='/login'), name='dispatch')
class HomepageView(TemplateView):
    template_name = "userpanel_mytag/base.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Cards'] = Card.objects.filter(created_by=self.request.user)
        return context


@method_decorator(login_required(login_url='/login'), name='dispatch')
class MyTagDetailView(DetailView):
    model = Card
    template_name = 'userpanel_mytag/user_panel_mytag_detail.html'

    def get_context_data(self, **kwargs):
        user_card = Card.objects.filter(pk=self.object.pk).first()
        if user_card is not None:
            if self.request.user == user_card.created_by:
                context = super(MyTagDetailView, self).get_context_data(**kwargs)
                return context
            else:
                raise Http404()
        raise Http404()


@method_decorator(login_required(login_url='/login'), name='dispatch')
class MyTagCreate(CreateView):
    model = Card
    template_name = 'userpanel_mytag/user_panel_mytag_create.html'
    form_class = CardForm
    success_url = None


    def get_context_data(self, **kwargs):
        data = super(MyTagCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['titles'] = ContactNumbersFormSet(self.request.POST)
            data['cards'] = CardSocialNetworkFormset(self.request.POST)
        else:
            data['titles'] = ContactNumbersFormSet()
            data['cards'] = CardSocialNetworkFormset()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        titles = context['titles']
        cards = context['cards']
        with transaction.atomic():
            form.instance.created_by = self.request.user
            form.instance.CardId = 222
            form.instance.BuildTime = datetime.datetime.now()
            form.instance.TypeOfCard_id = 1
            self.object = form.save()
            if titles.is_valid():
                titles.instance = self.object
                titles.save()
            if cards.is_valid():
                cards.instance = self.object
                cards.save()
        return super(MyTagCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('userpanel_mytag:detail', kwargs={'pk': self.object.pk})


@method_decorator(login_required(login_url='/login'), name='dispatch')
class MyTagUpdate(UpdateView):
    model = Card
    form_class = CardForm
    template_name = 'userpanel_mytag/user_panel_mytag_create.html'

    def get_context_data(self, **kwargs):
        user_card = Card.objects.filter(pk=self.object.pk).first()
        if user_card is not None:
            if self.request.user == user_card.created_by:
                data = super(MyTagUpdate, self).get_context_data(**kwargs)
                if self.request.POST:
                    data['titles'] = ContactNumbersFormSet(self.request.POST, instance=self.object)
                    data['cards'] = CardSocialNetworkFormset(self.request.POST, instance=self.object)
                else:
                    data['titles'] = ContactNumbersFormSet(instance=self.object)
                    data['cards'] = CardSocialNetworkFormset(instance=self.object)
                return data
            else:
                raise Http404()
        else:
            raise Http404()

    def form_valid(self, form):
        context = self.get_context_data()
        titles = context['titles']
        cards = context['cards']
        with transaction.atomic():
            form.instance.created_by = self.request.user
            self.object = form.save()
            if titles.is_valid():
                titles.instance = self.object
                titles.save()
            if cards.is_valid():
                cards.instance = self.object
                cards.save()
        return super(MyTagUpdate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('userpanel_mytag:homepage')


@method_decorator(login_required(login_url='/login'), name='dispatch')
class MyTagDelete(DeleteView):
    model = Card
    template_name = 'userpanel_mytag/user_panel_confirm_delete.html'
    success_url = reverse_lazy('userpanel_mytag:homepage')

userpanel_mytag/templates/userpanel_mytag/base.html
{% extends 'shared/userpanel/_MainLayout.html' %}
{% load static %}


{% block content %}
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">ویرایش تگ</h3>
                    </div>
                    <div class="box-body">
                        {% if Cards %}
                            {% for object in Cards %}

                                <li>
                                    <a href="{% url 'userpanel_mytag:detail' pk=object.pk %}"> تگ :
                                       {{ object }}</a>
                                </li>
                            {% endfor %}
                        {% else %}
                            <p>تگی ثبت نشده</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

userpanel_mytag/templates/userpanel_mytag/formset.html
{% load crispy_forms_tags %}
{% load static %}
<table class="col-md-9" style="margin-left: 10px;">
{{ formset.management_form|crispy }}

    {% for form in formset.forms %}
            <tr class="{% cycle 'row1' 'row2' %} formset_row-{{ formset.prefix }}">
                {% for field in form.visible_fields %}
                <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field|as_crispy_field }}
                </td>
                {% endfor %}
            </tr>
    {% endfor %}

</table>
<br>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src='{% static "dynamic_formsets/jquery.formset.js" %}'></script>
{#<script type="text/javascript">#}
    {#$('.formset_row-{{ formset.prefix }}').formset({#}
    {#    addText: 'add another',#}
    {#    deleteText: 'remove',#}
    {#    prefix: '{{ formset.prefix }}',#}
    {#});#}
{#</script>#}

userpanel_mytag/templates/userpanel_mytag/user_panel_confirm_delete.html
{% extends "userpanel_mytag/user_panel_mytag_detail.html" %}
{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm delete</h3>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>
                        Are you sure you want to delete: <strong>Collection ID {{ object }}</strong> ?
                    </h4>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                <input  class="btn btn-outline-secondary" type="submit" value="Cancel" onclick="goBack()" />
            </div>
        </div>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock content %}

userpanel_mytag/templates/userpanel_mytag/user_panel_mytag_create.html
{% extends "userpanel_mytag/base.html" %}
{% load crispy_forms_tags %}



{% block content %}
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">ویرایش تگ</h3>
                    </div>
                    <div class="box-body">
                        {% crispy form %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

userpanel_mytag/templates/userpanel_mytag/user_panel_mytag_detail.html
{% extends 'userpanel_mytag/base.html' %}
{% block content %}
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">ویرایش تگ</h3>
                    </div>
                    <table class="table">

                        {% if object.FirstName %}
                            <tr>
                                <th>نام</th>
                                <td>{{ object.FirstName }}</td>
                            </tr>
                        {% endif %}
                        {% if object.LastName %}
                            <tr>
                                <th>نام خانوادگی</th>
                                <td>{{ object.LastName }}</td>
                            </tr>
                        {% endif %}
                        {% if object.Company %}
                            <tr>
                                <th>شرکت</th>
                                <td>{{ object.Company }}</td>
                            </tr>
                            <tr>
                                <th>شغل</th>
                                <td>{{ object.WorkName }}</td>
                            </tr>

                        {% endif %}
                        {% if object.has_ContactNumbers %}
                            {% for title in object.has_ContactNumbers.all %}
                                <tr>
                                    <th>{{ title.Name }}</th>
                                    <td>{{ title.Number }}</td>
                                    <td>{{ title.Type }}</td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                        {% if object.socialnetwork_set %}
                            {% for title in object.socialnetwork_set.all %}
                                <tr>
                                    <th>{{ title.Name }}</th>
                                    <td>{{ title.Url }}</td>
                                    <td>{{ title.Type }}</td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                    </table>
                </div>
                <div class="card-body">
                    <a class="btn btn-outline-info" href="{% url 'userpanel_mytag:update' pk=object.id %}">ویرایش</a>
                    {#            <a class="btn btn-outline-danger" href="{% url 'userpanel_mytag:delete' pk=object.id %}">Delete</a>#}
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

userpanel_mytag/templates/userpanel_mytag/user_panel_mytag_home_page.html
{% extends 'shared/userpanel/_MainLayout.html' %}

{% block title %}
    پنل | تگ ها
{% endblock %}

{% block content %}
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">تگ ها</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <ul class="products-list product-list-in-box">
                {% for Card in Cards %}
                    <li class="item">
                        <div class="product-img">
                            <img src="{{ Card.ProfileImg.url }}" alt="Product Image">
                        </div>
                        <div class="product-info">
                            <a href="{% url 'userpanel_mytag:update' Card.id %}"
                               class="product-title">{{ Card.FirstName }} {{ Card.LastName }}</a>
                            <span class="product-description">
                          {{ Card.TypeOfCard.Name }}
                        </span>
                        </div>
                    </li>
                {% endfor %}


                <!-- /.item -->
            </ul>
        </div>
    </div>
    <!-- /.box-body -->
{% endblock %}